name: KHardcore
version: '${project.version}'
main: fr.kellotek.khardcore.KHardcore
api-version: '1.20'
authors: [KelloTek]
commands:
  revive:
    permission: khardcore.use.revive
  ritual:
    permission: khardcore.use.ritual
permissions:
  khardcore.use.revive:
    default: op
  khardcore.use.ritual:
    default: op